### ISSUE TITLE
Allow users to show their name on leaderboard

### ISSUE THREAD

**Issue by sebawild** [Powersort-Competition/PowersortCompetitionWebsite#1]
Add an option for a user to show submissions with their name in the table

Option 1:  They could pick a public nickname to show, that gets stored and shown; if none is set it shows “anonymous”

Option 2: If a nickname and/or an option is hard to do, I think I'd rather show names by default instead of never.  People do this voluntarily, and could open a fake-name account if needed.  But the leaderboard misses the fun if nobody can brag with being top.

**Comment by shayandoust** [comment]
For now, going with option #2. Will consider a changeable nickname further down the line.

**Comment by shayandoust** [comment]
Done, however might consider option #1 if time permits. For now, the other issue! :)
