### ISSUE TITLE
Clicking on “Merge Cost Difference” doesn't toggle Leaderboard back

### ISSUE THREAD

**Issue by sebawild** [Powersort-Competition/PowersortCompetitionWebsite#6]
* [x] The toggle buttons on the leaderboard don't toggle 🙃

* [x] Also good to double check that we get the actual top k from the database for each cost measure (not just resort in frontend).

Workaround: Reload the page to get mergecost; click comparisons to get those.

**Comment by sebawild** [comment]
@shayandoust From looking at the code, we indeed just resort the table, but we should get to different sets of top-k entries for the two cost measures.  Can you fix that?

**Comment by shayandoust** [comment]
> @shayandoust From looking at the code, we indeed just resort the table, but we should get to different sets of top-k entries for the two cost measures. Can you fix that?

Ahh yes you're right, completely glossed over that. I can fix it.
